
export interface Stock {
  symbol: string;
  name: string;
}

// Comprehensive list of active NSE Stocks (Nifty 500 subset + Popular F&O Stocks)
export const INDIAN_STOCKS: Stock[] = [
  // --- NIFTY 50 (Major Large Caps) ---
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries Ltd' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank Ltd' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank Ltd' },
  { symbol: 'INFY.NS', name: 'Infosys Ltd' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel Ltd' },
  { symbol: 'ITC.NS', name: 'ITC Ltd' },
  { symbol: 'SBIN.NS', name: 'State Bank of India' },
  { symbol: 'LICI.NS', name: 'Life Insurance Corporation of India' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever Ltd' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro Ltd' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance Ltd' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies Ltd' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India Ltd' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical Industries' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises Ltd' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank Ltd' },
  { symbol: 'TITAN.NS', name: 'Titan Company Ltd' },
  { symbol: 'ONGC.NS', name: 'Oil & Natural Gas Corporation' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors Ltd' },
  { symbol: 'NTPC.NS', name: 'NTPC Ltd' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank Ltd' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement Ltd' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corp of India' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel Ltd' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel Ltd' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra Ltd' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports & SEZ' },
  { symbol: 'COALINDIA.NS', name: 'Coal India Ltd' },
  { symbol: 'WIPRO.NS', name: 'Wipro Ltd' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries Ltd' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv Ltd' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries Ltd' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India Ltd' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra Ltd' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors Ltd' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries Ltd' },
  { symbol: 'CIPLA.NS', name: 'Cipla Ltd' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance Company' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy\'s Laboratories' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance Company' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank Ltd' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals Enterprise' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp Ltd' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum Corporation' },
  { symbol: 'DIVISLAB.NS', name: 'Divi\'s Laboratories Ltd' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree Ltd' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto Ltd' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints Ltd' },

  // --- NIFTY NEXT 50 & MIDCAP 150 ---
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics Ltd' },
  { symbol: 'DLF.NS', name: 'DLF Ltd' },
  { symbol: 'VBL.NS', name: 'Varun Beverages Ltd' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics Ltd' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy Ltd' },
  { symbol: 'ADANIPOWER.NS', name: 'Adani Power Ltd' },
  { symbol: 'PFC.NS', name: 'Power Finance Corporation' },
  { symbol: 'RECLTD.NS', name: 'REC Ltd' },
  { symbol: 'TRENT.NS', name: 'Trent Ltd' },
  { symbol: 'ZOMATO.NS', name: 'Zomato Ltd' },
  { symbol: 'JIOFIN.NS', name: 'Jio Financial Services Ltd' },
  { symbol: 'SIEMENS.NS', name: 'Siemens Ltd' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation Ltd' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals Ltd' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries Ltd' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts Ltd (DMart)' },
  { symbol: 'SRF.NS', name: 'SRF Ltd' },
  { symbol: 'GAIL.NS', name: 'GAIL (India) Ltd' },
  { symbol: 'VEDL.NS', name: 'Vedanta Ltd' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda' },
  { symbol: 'CANBK.NS', name: 'Canara Bank' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company Ltd' },
  { symbol: 'HAVELLS.NS', name: 'Havells India Ltd' },
  { symbol: 'DABUR.NS', name: 'Dabur India Ltd' },
  { symbol: 'ABB.NS', name: 'ABB India Ltd' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement Ltd' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements Ltd' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints India Ltd' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life Insurance' },
  { symbol: 'ICICIGI.NS', name: 'ICICI Lombard General Insurance' },
  { symbol: 'SBICARD.NS', name: 'SBI Cards and Payment Services' },
  { symbol: 'MARICO.NS', name: 'Marico Ltd' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge (India) Ltd' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Ltd' },
  { symbol: 'PIIND.NS', name: 'PI Industries Ltd' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries Ltd' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharmaceuticals Ltd' },
  { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson International' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation Ltd' },
  { symbol: 'UNITEDSPIRITS.NS', name: 'United Spirits Ltd' },
  { symbol: 'COLPAL.NS', name: 'Colgate-Palmolive (India) Ltd' },

  // --- POPULAR MIDCAPS & SMALLCAPS (High Retail Interest) ---
  { symbol: 'HINDCOPPER.NS', name: 'Hindustan Copper Ltd' },
  { symbol: 'POWERMECH.NS', name: 'Power Mech Projects Ltd' }, // Often searched as PWL
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corporation' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam Ltd' },
  { symbol: 'IRCON.NS', name: 'Ircon International Ltd' },
  { symbol: 'RAILTEL.NS', name: 'RailTel Corporation of India' },
  { symbol: 'TITAGARH.NS', name: 'Titagarh Rail Systems Ltd' },
  { symbol: 'TEXRAIL.NS', name: 'Texmaco Rail & Engineering' },
  { symbol: 'JWL.NS', name: 'Jupiter Wagons Ltd' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy Ltd' },
  { symbol: 'IDEA.NS', name: 'Vodafone Idea Ltd' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank Ltd' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank Ltd' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange Ltd' },
  { symbol: 'CDSL.NS', name: 'Central Depository Services Ltd' },
  { symbol: 'BSE.NS', name: 'BSE Limited' },
  { symbol: 'MCX.NS', name: 'Multi Commodity Exchange of India' },
  { symbol: 'CAMS.NS', name: 'Computer Age Management Services' },
  { symbol: 'ANGELONE.NS', name: 'Angel One Ltd' },
  { symbol: 'PAYTM.NS', name: 'One 97 Communications Ltd (Paytm)' },
  { symbol: 'NYKAA.NS', name: 'FSN E-Commerce Ventures (Nykaa)' },
  { symbol: 'POLICYBZR.NS', name: 'PB Fintech Ltd' },
  { symbol: 'DELHIVERY.NS', name: 'Delhivery Ltd' },
  { symbol: 'MAZDOCK.NS', name: 'Mazagon Dock Shipbuilders' },
  { symbol: 'COCHINSHIP.NS', name: 'Cochin Shipyard Ltd' },
  { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders' },
  { symbol: 'BDL.NS', name: 'Bharat Dynamics Ltd' },
  { symbol: 'DATAATT.NS', name: 'Data Patterns (India) Ltd' },
  { symbol: 'PARAS.NS', name: 'Paras Defence and Space Technologies' },
  { symbol: 'MTARTECH.NS', name: 'MTAR Technologies Ltd' },
  { symbol: 'ASTRAMICRO.NS', name: 'Astra Microwave Products' },
  { symbol: 'SOLARINDS.NS', name: 'Solar Industries India Ltd' },
  { symbol: 'BHEL.NS', name: 'Bharat Heavy Electricals Ltd' },
  { symbol: 'NHPC.NS', name: 'NHPC Ltd' },
  { symbol: 'SJVN.NS', name: 'SJVN Ltd' },
  { symbol: 'NLCINDIA.NS', name: 'NLC India Ltd' },
  { symbol: 'NBCC.NS', name: 'NBCC (India) Ltd' },
  { symbol: 'HUDCO.NS', name: 'HUDCO' },
  { symbol: 'MRPL.NS', name: 'Mangalore Refinery & Petrochemicals' },
  { symbol: 'CHENNPETRO.NS', name: 'Chennai Petroleum Corporation' },
  { symbol: 'GSFC.NS', name: 'Gujarat State Fertilizers & Chemicals' },
  { symbol: 'GNFC.NS', name: 'Gujarat Narmada Valley Fertilizers' },
  { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilisers' },
  { symbol: 'RCF.NS', name: 'Rashtriya Chemicals & Fertilizers' },
  { symbol: 'FACT.NS', name: 'Fertilisers and Chemicals Travancore' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium Company (NALCO)' },
  { symbol: 'SAIL.NS', name: 'Steel Authority of India Ltd' },
  { symbol: 'NMDC.NS', name: 'NMDC Ltd' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel & Power Ltd' },
  { symbol: 'JSL.NS', name: 'Jindal Stainless Ltd' },
  { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes Ltd' },
  { symbol: 'RATNAMANI.NS', name: 'Ratnamani Metals & Tubes' },
  { symbol: 'WELCORP.NS', name: 'Welspun Corp Ltd' },
  
  // --- IT & TECH (Mid/Small) ---
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies Ltd' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi Ltd' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree Ltd' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems Ltd' },
  { symbol: 'COFORGE.NS', name: 'Coforge Ltd' },
  { symbol: 'LTTS.NS', name: 'L&T Technology Services Ltd' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Ltd' },
  { symbol: 'CYIENT.NS', name: 'Cyient Ltd' },
  { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies Ltd' },
  { symbol: 'SONATSOFTW.NS', name: 'Sonata Software Ltd' },
  { symbol: 'INTELLECT.NS', name: 'Intellect Design Arena' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds Technologies' },
  { symbol: 'TANLA.NS', name: 'Tanla Platforms Ltd' },
  { symbol: 'BSOFT.NS', name: 'Birlasoft Ltd' },
  { symbol: 'MASTEK.NS', name: 'Mastek Ltd' },
  { symbol: 'NAZARA.NS', name: 'Nazara Technologies Ltd' },
  { symbol: 'RATEGAIN.NS', name: 'RateGain Travel Technologies' },
  { symbol: 'MAPMYINDIA.NS', name: 'C.E. Info Systems (MapmyIndia)' },
  { symbol: 'TRIDENT.NS', name: 'Trident Ltd' },
  { symbol: 'RAYMOND.NS', name: 'Raymond Ltd' },
  { symbol: 'WELSPUNLIV.NS', name: 'Welspun Living Ltd' },
  { symbol: 'ALOKINDS.NS', name: 'Alok Industries Ltd' },

  // --- BANKS (PSU & Private Mid) ---
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank' },
  { symbol: 'CENTRALBK.NS', name: 'Central Bank of India' },
  { symbol: 'BANKINDIA.NS', name: 'Bank of India' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra' },
  { symbol: 'PSB.NS', name: 'Punjab & Sind Bank' },
  { symbol: 'J&KBANK.NS', name: 'Jammu & Kashmir Bank' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank' },
  { symbol: 'FEDERALBNK.NS', name: 'The Federal Bank Ltd' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank Ltd' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank Ltd' },
  { symbol: 'CUB.NS', name: 'City Union Bank Ltd' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank' },
  { symbol: 'SOUTHBANK.NS', name: 'The South Indian Bank' },
  { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance Bank' },
  { symbol: 'UJJIVANSFB.NS', name: 'Ujjivan Small Finance Bank' },

  // --- INFRA & REALTY ---
  { symbol: 'LODHA.NS', name: 'Macrotech Developers Ltd' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties Ltd' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty Ltd' },
  { symbol: 'PHOENIXLTD.NS', name: 'The Phoenix Mills Ltd' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates Projects' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises Ltd' },
  { symbol: 'SOBHA.NS', name: 'Sobha Ltd' },
  { symbol: 'NCC.NS', name: 'NCC Limited' },
  { symbol: 'KNRCON.NS', name: 'KNR Constructions Ltd' },
  { symbol: 'PNCINFRA.NS', name: 'PNC Infratech Ltd' },
  { symbol: 'IRB.NS', name: 'IRB Infrastructure Developers' },
  { symbol: 'GMRINFRA.NS', name: 'GMR Airports Infrastructure' },
  { symbol: 'ENGINERSIN.NS', name: 'Engineers India Ltd' },
  
  // --- AUTOMOTIVE & ANCILLARY ---
  { symbol: 'MRF.NS', name: 'MRF Ltd' },
  { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres Ltd' },
  { symbol: 'JKTYRE.NS', name: 'JK Tyre & Industries Ltd' },
  { symbol: 'CEATLTD.NS', name: 'CEAT Ltd' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries Ltd' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge Ltd' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision Forgings' },
  { symbol: 'UNO_MINDA.NS', name: 'Uno Minda Ltd' },
  { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries Ltd' },
  { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Energy & Mobility' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland Ltd' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Kubota Ltd' },
  { symbol: 'JBMA.NS', name: 'JBM Auto Ltd' },
  { symbol: 'OLECTRA.NS', name: 'Olectra Greentech Ltd' },

  // --- CHEMICALS ---
  { symbol: 'UPL.NS', name: 'UPL Ltd' },
  { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite Ltd' },
  { symbol: 'AARTIIND.NS', name: 'Aarti Industries Ltd' },
  { symbol: 'ATUL.NS', name: 'Atul Ltd' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine International' },
  { symbol: 'VINATIORGA.NS', name: 'Vinati Organics Ltd' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India Ltd' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories Ltd' },
  
  // --- OTHERS (Media, Consumer, Etc) ---
  { symbol: 'SUNTV.NS', name: 'Sun TV Network Ltd' },
  { symbol: 'ZEEL.NS', name: 'Zee Entertainment Enterprises' },
  { symbol: 'PVRINOX.NS', name: 'PVR INOX Ltd' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks Ltd' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International Ltd' },
  { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods India' },
  { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld Ltd' },
  { symbol: 'INDHOTEL.NS', name: 'The Indian Hotels Company' },
  { symbol: 'EIHOTEL.NS', name: 'EIH Ltd' },
  { symbol: 'CHALET.NS', name: 'Chalet Hotels Ltd' },
  { symbol: 'LEMONTREE.NS', name: 'Lemon Tree Hotels Ltd' },
  { symbol: 'BLS.NS', name: 'BLS International Services' },
  { symbol: 'REDINGTON.NS', name: 'Redington Ltd' },
  { symbol: 'KEI.NS', name: 'KEI Industries Ltd' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India Ltd' },
  { symbol: 'RRKABEL.NS', name: 'RR Kabel Ltd' },
  { symbol: 'VGUARD.NS', name: 'V-Guard Industries Ltd' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies (India)' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises India' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics Ltd' },
  { symbol: 'CERA.NS', name: 'Cera Sanitaryware Ltd' },
  { symbol: 'ASTRAL.NS', name: 'Astral Ltd' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries Ltd' },
  { symbol: 'FINCABLES.NS', name: 'Finolex Cables Ltd' }
];
